//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\RichieZ\repos\logix\examples\d2\d2-plugin\code\D2Assembly\D2Assembly.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace D2Plugin {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class D2AssemblyParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, INSTRUCTION=19, LABEL=20, BINARY=21, HEXADECIMAL=22, DECIMAL=23, 
		NEWLINE=24, WS=25, STRINGLITERAL=26, COMMENT=27;
	public const int
		RULE_prog = 0, RULE_line = 1, RULE_constantline = 2, RULE_directiveline = 3, 
		RULE_directive = 4, RULE_orgdir = 5, RULE_worddir = 6, RULE_asciizdir = 7, 
		RULE_dbdir = 8, RULE_instrline = 9, RULE_symbolline = 10, RULE_symbol = 11, 
		RULE_argument = 12, RULE_immediate = 13, RULE_number = 14;
	public static readonly string[] ruleNames = {
		"prog", "line", "constantline", "directiveline", "directive", "orgdir", 
		"worddir", "asciizdir", "dbdir", "instrline", "symbolline", "symbol", 
		"argument", "immediate", "number"
	};

	private static readonly string[] _LiteralNames = {
		null, "'='", "'.'", "'org'", "'word'", "'asciiz'", "'db'", "','", "':'", 
		"'x'", "'y'", "'#'", "'('", "'+'", "')'", "'-'", "'*'", "'&'", "'|'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, "INSTRUCTION", "LABEL", "BINARY", 
		"HEXADECIMAL", "DECIMAL", "NEWLINE", "WS", "STRINGLITERAL", "COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "D2Assembly.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static D2AssemblyParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public D2AssemblyParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public D2AssemblyParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(D2AssemblyParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 33;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << INSTRUCTION) | (1L << LABEL))) != 0)) {
				{
				{
				State = 30;
				line();
				}
				}
				State = 35;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 36;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SymbollineContext symbolline() {
			return GetRuleContext<SymbollineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstrlineContext instrline() {
			return GetRuleContext<InstrlineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DirectivelineContext directiveline() {
			return GetRuleContext<DirectivelineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConstantlineContext constantline() {
			return GetRuleContext<ConstantlineContext>(0);
		}
		public LineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_line; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LineContext line() {
		LineContext _localctx = new LineContext(Context, State);
		EnterRule(_localctx, 2, RULE_line);
		try {
			State = 42;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 38;
				symbolline();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 39;
				instrline();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 40;
				directiveline();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 41;
				constantline();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstantlineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LABEL() { return GetToken(D2AssemblyParser.LABEL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BINARY() { return GetToken(D2AssemblyParser.BINARY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HEXADECIMAL() { return GetToken(D2AssemblyParser.HEXADECIMAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL() { return GetToken(D2AssemblyParser.DECIMAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEWLINE() { return GetTokens(D2AssemblyParser.NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE(int i) {
			return GetToken(D2AssemblyParser.NEWLINE, i);
		}
		public ConstantlineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constantline; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstantline(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConstantlineContext constantline() {
		ConstantlineContext _localctx = new ConstantlineContext(Context, State);
		EnterRule(_localctx, 4, RULE_constantline);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 44;
			Match(LABEL);
			State = 45;
			Match(T__0);
			State = 46;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << BINARY) | (1L << HEXADECIMAL) | (1L << DECIMAL))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 48;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 47;
				Match(NEWLINE);
				}
				}
				State = 50;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==NEWLINE );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DirectivelineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DirectiveContext directive() {
			return GetRuleContext<DirectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SymbolContext symbol() {
			return GetRuleContext<SymbolContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEWLINE() { return GetTokens(D2AssemblyParser.NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE(int i) {
			return GetToken(D2AssemblyParser.NEWLINE, i);
		}
		public DirectivelineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directiveline; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDirectiveline(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DirectivelineContext directiveline() {
		DirectivelineContext _localctx = new DirectivelineContext(Context, State);
		EnterRule(_localctx, 6, RULE_directiveline);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LABEL) {
				{
				State = 52;
				symbol();
				}
			}

			State = 55;
			directive();
			State = 57;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 56;
				Match(NEWLINE);
				}
				}
				State = 59;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==NEWLINE );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DirectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OrgdirContext orgdir() {
			return GetRuleContext<OrgdirContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WorddirContext worddir() {
			return GetRuleContext<WorddirContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AsciizdirContext asciizdir() {
			return GetRuleContext<AsciizdirContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DbdirContext dbdir() {
			return GetRuleContext<DbdirContext>(0);
		}
		public DirectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directive; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDirective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DirectiveContext directive() {
		DirectiveContext _localctx = new DirectiveContext(Context, State);
		EnterRule(_localctx, 8, RULE_directive);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			Match(T__1);
			State = 66;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__2:
				{
				State = 62;
				orgdir();
				}
				break;
			case T__3:
				{
				State = 63;
				worddir();
				}
				break;
			case T__4:
				{
				State = 64;
				asciizdir();
				}
				break;
			case T__5:
				{
				State = 65;
				dbdir();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrgdirContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public OrgdirContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_orgdir; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrgdir(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrgdirContext orgdir() {
		OrgdirContext _localctx = new OrgdirContext(Context, State);
		EnterRule(_localctx, 10, RULE_orgdir);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68;
			Match(T__2);
			State = 69;
			number();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WorddirContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public WorddirContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_worddir; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWorddir(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WorddirContext worddir() {
		WorddirContext _localctx = new WorddirContext(Context, State);
		EnterRule(_localctx, 12, RULE_worddir);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71;
			Match(T__3);
			State = 72;
			number();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AsciizdirContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGLITERAL() { return GetToken(D2AssemblyParser.STRINGLITERAL, 0); }
		public AsciizdirContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_asciizdir; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAsciizdir(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AsciizdirContext asciizdir() {
		AsciizdirContext _localctx = new AsciizdirContext(Context, State);
		EnterRule(_localctx, 14, RULE_asciizdir);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			Match(T__4);
			State = 75;
			Match(STRINGLITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DbdirContext : ParserRuleContext {
		public NumberContext _number;
		public IList<NumberContext> _nums = new List<NumberContext>();
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext[] number() {
			return GetRuleContexts<NumberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number(int i) {
			return GetRuleContext<NumberContext>(i);
		}
		public DbdirContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dbdir; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDbdir(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DbdirContext dbdir() {
		DbdirContext _localctx = new DbdirContext(Context, State);
		EnterRule(_localctx, 16, RULE_dbdir);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77;
			Match(T__5);
			State = 78;
			_localctx._number = number();
			_localctx._nums.Add(_localctx._number);
			State = 83;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__6) {
				{
				{
				State = 79;
				Match(T__6);
				State = 80;
				_localctx._number = number();
				_localctx._nums.Add(_localctx._number);
				}
				}
				State = 85;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstrlineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INSTRUCTION() { return GetToken(D2AssemblyParser.INSTRUCTION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SymbolContext symbol() {
			return GetRuleContext<SymbolContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument() {
			return GetRuleContext<ArgumentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEWLINE() { return GetTokens(D2AssemblyParser.NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE(int i) {
			return GetToken(D2AssemblyParser.NEWLINE, i);
		}
		public InstrlineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instrline; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstrline(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InstrlineContext instrline() {
		InstrlineContext _localctx = new InstrlineContext(Context, State);
		EnterRule(_localctx, 18, RULE_instrline);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LABEL) {
				{
				State = 86;
				symbol();
				}
			}

			State = 89;
			Match(INSTRUCTION);
			State = 91;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__10) | (1L << T__11) | (1L << LABEL) | (1L << BINARY) | (1L << HEXADECIMAL) | (1L << DECIMAL))) != 0)) {
				{
				State = 90;
				argument();
				}
			}

			State = 94;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 93;
				Match(NEWLINE);
				}
				}
				State = 96;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==NEWLINE );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SymbollineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SymbolContext symbol() {
			return GetRuleContext<SymbolContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEWLINE() { return GetTokens(D2AssemblyParser.NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE(int i) {
			return GetToken(D2AssemblyParser.NEWLINE, i);
		}
		public SymbollineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_symbolline; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSymbolline(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SymbollineContext symbolline() {
		SymbollineContext _localctx = new SymbollineContext(Context, State);
		EnterRule(_localctx, 20, RULE_symbolline);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98;
			symbol();
			State = 100;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 99;
				Match(NEWLINE);
				}
				}
				State = 102;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==NEWLINE );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SymbolContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LABEL() { return GetToken(D2AssemblyParser.LABEL, 0); }
		public SymbolContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_symbol; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSymbol(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SymbolContext symbol() {
		SymbolContext _localctx = new SymbolContext(Context, State);
		EnterRule(_localctx, 22, RULE_symbol);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104;
			Match(LABEL);
			State = 105;
			Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		public IToken x;
		public IToken y;
		[System.Diagnostics.DebuggerNonUserCode] public ImmediateContext immediate() {
			return GetRuleContext<ImmediateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 24, RULE_argument);
		try {
			State = 117;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 107;
				immediate();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 108;
				number();
				State = 109;
				Match(T__6);
				State = 110;
				_localctx.x = Match(T__8);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 112;
				number();
				State = 113;
				Match(T__6);
				State = 114;
				_localctx.y = Match(T__9);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 116;
				number();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImmediateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public ImmediateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_immediate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImmediate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImmediateContext immediate() {
		ImmediateContext _localctx = new ImmediateContext(Context, State);
		EnterRule(_localctx, 26, RULE_immediate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			Match(T__10);
			State = 120;
			number();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		public IToken bin;
		public IToken hex;
		public IToken dec;
		public IToken lab;
		public IToken plus;
		public IToken minus;
		public IToken mult;
		public IToken and;
		public IToken or;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BINARY() { return GetToken(D2AssemblyParser.BINARY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HEXADECIMAL() { return GetToken(D2AssemblyParser.HEXADECIMAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL() { return GetToken(D2AssemblyParser.DECIMAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LABEL() { return GetToken(D2AssemblyParser.LABEL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext[] number() {
			return GetRuleContexts<NumberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number(int i) {
			return GetRuleContext<NumberContext>(i);
		}
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ID2AssemblyVisitor<TResult> typedVisitor = visitor as ID2AssemblyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 28, RULE_number);
		try {
			State = 156;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 122;
				_localctx.bin = Match(BINARY);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 123;
				_localctx.hex = Match(HEXADECIMAL);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 124;
				_localctx.dec = Match(DECIMAL);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 125;
				_localctx.lab = Match(LABEL);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 126;
				Match(T__11);
				State = 127;
				number();
				State = 128;
				_localctx.plus = Match(T__12);
				State = 129;
				number();
				State = 130;
				Match(T__13);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 132;
				Match(T__11);
				State = 133;
				number();
				State = 134;
				_localctx.minus = Match(T__14);
				State = 135;
				number();
				State = 136;
				Match(T__13);
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 138;
				Match(T__11);
				State = 139;
				number();
				State = 140;
				_localctx.mult = Match(T__15);
				State = 141;
				number();
				State = 142;
				Match(T__13);
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 144;
				Match(T__11);
				State = 145;
				number();
				State = 146;
				_localctx.and = Match(T__16);
				State = 147;
				number();
				State = 148;
				Match(T__13);
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 150;
				Match(T__11);
				State = 151;
				number();
				State = 152;
				_localctx.or = Match(T__17);
				State = 153;
				number();
				State = 154;
				Match(T__13);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x1D', '\xA1', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\a', '\x2', '\"', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '%', 
		'\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x5', '\x3', '-', '\n', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x6', '\x4', '\x33', '\n', '\x4', 
		'\r', '\x4', '\xE', '\x4', '\x34', '\x3', '\x5', '\x5', '\x5', '\x38', 
		'\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x6', '\x5', '<', '\n', '\x5', 
		'\r', '\x5', '\xE', '\x5', '=', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x45', '\n', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\a', '\n', 'T', '\n', '\n', '\f', '\n', '\xE', '\n', 
		'W', '\v', '\n', '\x3', '\v', '\x5', '\v', 'Z', '\n', '\v', '\x3', '\v', 
		'\x3', '\v', '\x5', '\v', '^', '\n', '\v', '\x3', '\v', '\x6', '\v', '\x61', 
		'\n', '\v', '\r', '\v', '\xE', '\v', '\x62', '\x3', '\f', '\x3', '\f', 
		'\x6', '\f', 'g', '\n', '\f', '\r', '\f', '\xE', '\f', 'h', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x5', '\xE', 'x', '\n', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x5', '\x10', '\x9F', '\n', '\x10', '\x3', '\x10', '\x2', '\x2', 
		'\x11', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', '\x2', '\x3', '\x3', '\x2', 
		'\x17', '\x19', '\x2', '\xAB', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x4', ',', '\x3', '\x2', '\x2', '\x2', '\x6', '.', '\x3', '\x2', '\x2', 
		'\x2', '\b', '\x37', '\x3', '\x2', '\x2', '\x2', '\n', '?', '\x3', '\x2', 
		'\x2', '\x2', '\f', '\x46', '\x3', '\x2', '\x2', '\x2', '\xE', 'I', '\x3', 
		'\x2', '\x2', '\x2', '\x10', 'L', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'O', '\x3', '\x2', '\x2', '\x2', '\x14', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'\x16', '\x64', '\x3', '\x2', '\x2', '\x2', '\x18', 'j', '\x3', '\x2', 
		'\x2', '\x2', '\x1A', 'w', '\x3', '\x2', '\x2', '\x2', '\x1C', 'y', '\x3', 
		'\x2', '\x2', '\x2', '\x1E', '\x9E', '\x3', '\x2', '\x2', '\x2', ' ', 
		'\"', '\x5', '\x4', '\x3', '\x2', '!', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\"', '%', '\x3', '\x2', '\x2', '\x2', '#', '!', '\x3', '\x2', '\x2', 
		'\x2', '#', '$', '\x3', '\x2', '\x2', '\x2', '$', '&', '\x3', '\x2', '\x2', 
		'\x2', '%', '#', '\x3', '\x2', '\x2', '\x2', '&', '\'', '\a', '\x2', '\x2', 
		'\x3', '\'', '\x3', '\x3', '\x2', '\x2', '\x2', '(', '-', '\x5', '\x16', 
		'\f', '\x2', ')', '-', '\x5', '\x14', '\v', '\x2', '*', '-', '\x5', '\b', 
		'\x5', '\x2', '+', '-', '\x5', '\x6', '\x4', '\x2', ',', '(', '\x3', '\x2', 
		'\x2', '\x2', ',', ')', '\x3', '\x2', '\x2', '\x2', ',', '*', '\x3', '\x2', 
		'\x2', '\x2', ',', '+', '\x3', '\x2', '\x2', '\x2', '-', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '.', '/', '\a', '\x16', '\x2', '\x2', '/', '\x30', 
		'\a', '\x3', '\x2', '\x2', '\x30', '\x32', '\t', '\x2', '\x2', '\x2', 
		'\x31', '\x33', '\a', '\x1A', '\x2', '\x2', '\x32', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x33', '\x34', '\x3', '\x2', '\x2', '\x2', '\x34', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\a', '\x3', '\x2', '\x2', '\x2', '\x36', '\x38', '\x5', '\x18', 
		'\r', '\x2', '\x37', '\x36', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', 
		'\x3', '\x2', '\x2', '\x2', '\x38', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\x39', ';', '\x5', '\n', '\x6', '\x2', ':', '<', '\a', '\x1A', '\x2', 
		'\x2', ';', ':', '\x3', '\x2', '\x2', '\x2', '<', '=', '\x3', '\x2', '\x2', 
		'\x2', '=', ';', '\x3', '\x2', '\x2', '\x2', '=', '>', '\x3', '\x2', '\x2', 
		'\x2', '>', '\t', '\x3', '\x2', '\x2', '\x2', '?', '\x44', '\a', '\x4', 
		'\x2', '\x2', '@', '\x45', '\x5', '\f', '\a', '\x2', '\x41', '\x45', '\x5', 
		'\xE', '\b', '\x2', '\x42', '\x45', '\x5', '\x10', '\t', '\x2', '\x43', 
		'\x45', '\x5', '\x12', '\n', '\x2', '\x44', '@', '\x3', '\x2', '\x2', 
		'\x2', '\x44', '\x41', '\x3', '\x2', '\x2', '\x2', '\x44', '\x42', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\v', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\a', '\x5', '\x2', '\x2', 
		'G', 'H', '\x5', '\x1E', '\x10', '\x2', 'H', '\r', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'J', '\a', '\x6', '\x2', '\x2', 'J', 'K', '\x5', '\x1E', '\x10', 
		'\x2', 'K', '\xF', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', '\a', '\x2', 
		'\x2', 'M', 'N', '\a', '\x1C', '\x2', '\x2', 'N', '\x11', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\a', '\b', '\x2', '\x2', 'P', 'U', '\x5', '\x1E', 
		'\x10', '\x2', 'Q', 'R', '\a', '\t', '\x2', '\x2', 'R', 'T', '\x5', '\x1E', 
		'\x10', '\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'T', 'W', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'V', '\x13', '\x3', '\x2', '\x2', '\x2', 'W', 'U', 
		'\x3', '\x2', '\x2', '\x2', 'X', 'Z', '\x5', '\x18', '\r', '\x2', 'Y', 
		'X', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', ']', '\a', '\x15', '\x2', '\x2', 
		'\\', '^', '\x5', '\x1A', '\xE', '\x2', ']', '\\', '\x3', '\x2', '\x2', 
		'\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '`', '\x3', '\x2', '\x2', 
		'\x2', '_', '\x61', '\a', '\x1A', '\x2', '\x2', '`', '_', '\x3', '\x2', 
		'\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', '\x2', '\x62', '`', 
		'\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\x3', '\x2', '\x2', '\x2', 
		'\x63', '\x15', '\x3', '\x2', '\x2', '\x2', '\x64', '\x66', '\x5', '\x18', 
		'\r', '\x2', '\x65', 'g', '\a', '\x1A', '\x2', '\x2', '\x66', '\x65', 
		'\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 'h', 
		'\x66', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x3', '\x2', '\x2', '\x2', 
		'i', '\x17', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', '\x16', '\x2', 
		'\x2', 'k', 'l', '\a', '\n', '\x2', '\x2', 'l', '\x19', '\x3', '\x2', 
		'\x2', '\x2', 'm', 'x', '\x5', '\x1C', '\xF', '\x2', 'n', 'o', '\x5', 
		'\x1E', '\x10', '\x2', 'o', 'p', '\a', '\t', '\x2', '\x2', 'p', 'q', '\a', 
		'\v', '\x2', '\x2', 'q', 'x', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x5', 
		'\x1E', '\x10', '\x2', 's', 't', '\a', '\t', '\x2', '\x2', 't', 'u', '\a', 
		'\f', '\x2', '\x2', 'u', 'x', '\x3', '\x2', '\x2', '\x2', 'v', 'x', '\x5', 
		'\x1E', '\x10', '\x2', 'w', 'm', '\x3', '\x2', '\x2', '\x2', 'w', 'n', 
		'\x3', '\x2', '\x2', '\x2', 'w', 'r', '\x3', '\x2', '\x2', '\x2', 'w', 
		'v', '\x3', '\x2', '\x2', '\x2', 'x', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'y', 'z', '\a', '\r', '\x2', '\x2', 'z', '{', '\x5', '\x1E', '\x10', '\x2', 
		'{', '\x1D', '\x3', '\x2', '\x2', '\x2', '|', '\x9F', '\a', '\x17', '\x2', 
		'\x2', '}', '\x9F', '\a', '\x18', '\x2', '\x2', '~', '\x9F', '\a', '\x19', 
		'\x2', '\x2', '\x7F', '\x9F', '\a', '\x16', '\x2', '\x2', '\x80', '\x81', 
		'\a', '\xE', '\x2', '\x2', '\x81', '\x82', '\x5', '\x1E', '\x10', '\x2', 
		'\x82', '\x83', '\a', '\xF', '\x2', '\x2', '\x83', '\x84', '\x5', '\x1E', 
		'\x10', '\x2', '\x84', '\x85', '\a', '\x10', '\x2', '\x2', '\x85', '\x9F', 
		'\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', '\xE', '\x2', '\x2', 
		'\x87', '\x88', '\x5', '\x1E', '\x10', '\x2', '\x88', '\x89', '\a', '\x11', 
		'\x2', '\x2', '\x89', '\x8A', '\x5', '\x1E', '\x10', '\x2', '\x8A', '\x8B', 
		'\a', '\x10', '\x2', '\x2', '\x8B', '\x9F', '\x3', '\x2', '\x2', '\x2', 
		'\x8C', '\x8D', '\a', '\xE', '\x2', '\x2', '\x8D', '\x8E', '\x5', '\x1E', 
		'\x10', '\x2', '\x8E', '\x8F', '\a', '\x12', '\x2', '\x2', '\x8F', '\x90', 
		'\x5', '\x1E', '\x10', '\x2', '\x90', '\x91', '\a', '\x10', '\x2', '\x2', 
		'\x91', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', '\xE', 
		'\x2', '\x2', '\x93', '\x94', '\x5', '\x1E', '\x10', '\x2', '\x94', '\x95', 
		'\a', '\x13', '\x2', '\x2', '\x95', '\x96', '\x5', '\x1E', '\x10', '\x2', 
		'\x96', '\x97', '\a', '\x10', '\x2', '\x2', '\x97', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\x98', '\x99', '\a', '\xE', '\x2', '\x2', '\x99', '\x9A', 
		'\x5', '\x1E', '\x10', '\x2', '\x9A', '\x9B', '\a', '\x14', '\x2', '\x2', 
		'\x9B', '\x9C', '\x5', '\x1E', '\x10', '\x2', '\x9C', '\x9D', '\a', '\x10', 
		'\x2', '\x2', '\x9D', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9E', '|', 
		'\x3', '\x2', '\x2', '\x2', '\x9E', '}', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x80', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xF', '#', ',', '\x34', 
		'\x37', '=', '\x44', 'U', 'Y', ']', '\x62', 'h', 'w', '\x9E',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace D2Plugin
