//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Daniel\winrepos\logix\examples\d2\d2-plugin\code\D2Assembly\D2Assembly.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="D2AssemblyParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ID2AssemblyVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] D2AssemblyParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] D2AssemblyParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.constantline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantline([NotNull] D2AssemblyParser.ConstantlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.directiveline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirectiveline([NotNull] D2AssemblyParser.DirectivelineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirective([NotNull] D2AssemblyParser.DirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.orgdir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrgdir([NotNull] D2AssemblyParser.OrgdirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.worddir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWorddir([NotNull] D2AssemblyParser.WorddirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.asciizdir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsciizdir([NotNull] D2AssemblyParser.AsciizdirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.dbdir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDbdir([NotNull] D2AssemblyParser.DbdirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.instrline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstrline([NotNull] D2AssemblyParser.InstrlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.symbolline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbolline([NotNull] D2AssemblyParser.SymbollineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbol([NotNull] D2AssemblyParser.SymbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] D2AssemblyParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImmediate([NotNull] D2AssemblyParser.ImmediateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2AssemblyParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] D2AssemblyParser.NumberContext context);
}
