//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/dcronqvist/repos/logix/assets/plugins/flisp-plugin/code/FLISPAssemblyLang/FLISPAssembly.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FLISPAssemblyParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IFLISPAssemblyVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] FLISPAssemblyParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.linelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinelist([NotNull] FLISPAssemblyParser.LinelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] FLISPAssemblyParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirective([NotNull] FLISPAssemblyParser.DirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.orgdir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrgdir([NotNull] FLISPAssemblyParser.OrgdirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.equdir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqudir([NotNull] FLISPAssemblyParser.EqudirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.fcbdir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFcbdir([NotNull] FLISPAssemblyParser.FcbdirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.fcsdir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFcsdir([NotNull] FLISPAssemblyParser.FcsdirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.rmbdir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRmbdir([NotNull] FLISPAssemblyParser.RmbdirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstr([NotNull] FLISPAssemblyParser.InstrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.numberlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberlist([NotNull] FLISPAssemblyParser.NumberlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImmediate([NotNull] FLISPAssemblyParser.ImmediateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPAssemblyParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] FLISPAssemblyParser.NumberContext context);
}
