---@meta
--- This file is auto-generated by LogiX. Do not modify.

---@type lua_data_entry[]
data = {}
defs = {}

---@type integer
local scripting_data_type_node

---@enum scripting_data_type
defs.scripting_data_type = {
  node = scripting_data_type_node,
}

---@type integer
local log_level_debug

---@type integer
local log_level_info

---@type integer
local log_level_warning

---@type integer
local log_level_error

---@type integer
local log_level_fatal

---@enum log_level
defs.log_level = {
  debug = log_level_debug,
  info = log_level_info,
  warning = log_level_warning,
  error = log_level_error,
  fatal = log_level_fatal,
}

---@type integer
local logic_value_low

---@type integer
local logic_value_high

---@type integer
local logic_value_undefined

---@enum logic_value
defs.logic_value = {
  low = logic_value_low,
  high = logic_value_high,
  undefined = logic_value_undefined,
}

---@type integer
local pin_side_left

---@type integer
local pin_side_right

---@type integer
local pin_side_top

---@type integer
local pin_side_bottom

---@enum pin_side
defs.pin_side = {
  left = pin_side_left,
  right = pin_side_right,
  top = pin_side_top,
  bottom = pin_side_bottom,
}

