---@meta
--- This file is auto-generated by LogiX. Do not modify.

---@deprecated
---@diagnostic disable-next-line: duplicate-set-field
function import() end -- Do not use this function. It has been sandboxed away

---@param num number
---@param numDecimalPlaces integer
---@return number
---@diagnostic disable-next-line: missing-return, duplicate-set-field
function round(num, numDecimalPlaces) end -- Rounds a number to a given number of decimal places

---@generic T
---@param table T[]
---@param key string
---@param value any
---@return T
---@diagnostic disable-next-line: missing-return, duplicate-set-field
function find(table, key, value) end -- Finds a value in a table by a given key and value

---@generic T
---@param orig T
---@return T
---@diagnostic disable-next-line: missing-return, duplicate-set-field
function deepcopy(orig) end -- Deep copies a value (including tables)

---@param file string
---@return any
---@diagnostic disable-next-line: missing-return, duplicate-set-field
function require(file) end -- Requires a script

---@param t1 table
---@param t2 table
---@diagnostic disable-next-line: duplicate-set-field
function table.extend(t1, t2) end -- Extends a table with another table, in place

---@param t1 table
---@param t2 table
---@return table
---@diagnostic disable-next-line: missing-return, duplicate-set-field
function table.concat(t1, t2) end -- Extends a table with another table, in place

---@param logLevel log_level
---@param s string
---@diagnostic disable-next-line: duplicate-set-field
function log(logLevel, s) end -- Logs a message

---@param id string
---@return string
---@diagnostic disable-next-line: missing-return, duplicate-set-field
function new_id(id) end -- Creates a new identifier, with the given id as a suffix to the script source identifier

