---@meta
--- This file is auto-generated by LogiX. Do not modify.

---@class lua_data_entry
---@field datatype scripting_data_type
---@field id string

---@class pin_config
---@field id string
---@field bit_width integer
---@field update_causes_evaluation boolean
---@field position vector2i
---@field side pin_side
---@field display_pin_name boolean

---@class vector2i
---@field x integer
---@field y integer

---@class pin_event
---@field pin_id string
---@field new_values logic_value[]
---@field occurs_in_ticks integer

---@class color_f
---@field r number
---@field g number
---@field b number
---@field a number

