//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\RichieZ\repos\logix\src\LogiX\Minimal\ActionSequencing\ANTLR\ActionSequence.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LogiX.Minimal.ActionSequencing {
#pragma warning disable 3021
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class ActionSequenceLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, BINARY_LITERAL=22, HEX_LITERAL=23, 
		DECIMAL_LITERAL=24, STRING_LITERAL=25, PIN_ID=26, WHITESPACE=27, LINECOMMENT=28;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "T__18", "T__19", "T__20", "BINARY_LITERAL", "HEX_LITERAL", "DECIMAL_LITERAL", 
		"STRING_LITERAL", "PIN_ID", "WHITESPACE", "LINECOMMENT"
	};


	public ActionSequenceLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ActionSequenceLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'wait'", "' '", "'set'", "'='", "'end'", "'continue'", "'print'", 
		"'push'", "','", "'connect_keyboard'", "'connect_tty'", "'mount_disk'", 
		"'['", "']'", "'=='", "'!='", "'&&'", "'||'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, "BINARY_LITERAL", 
		"HEX_LITERAL", "DECIMAL_LITERAL", "STRING_LITERAL", "PIN_ID", "WHITESPACE", 
		"LINECOMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ActionSequence.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ActionSequenceLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1E', '\xD5', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x6', '\x17', '\xA5', '\n', '\x17', '\r', '\x17', '\xE', '\x17', '\xA6', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x6', '\x18', 
		'\xAD', '\n', '\x18', '\r', '\x18', '\xE', '\x18', '\xAE', '\x3', '\x19', 
		'\x6', '\x19', '\xB2', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\xB3', 
		'\x3', '\x1A', '\x3', '\x1A', '\a', '\x1A', '\xB8', '\n', '\x1A', '\f', 
		'\x1A', '\xE', '\x1A', '\xBB', '\v', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1B', '\x6', '\x1B', '\xC0', '\n', '\x1B', '\r', '\x1B', '\xE', 
		'\x1B', '\xC1', '\x3', '\x1C', '\x6', '\x1C', '\xC5', '\n', '\x1C', '\r', 
		'\x1C', '\xE', '\x1C', '\xC6', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\a', '\x1D', '\xCF', '\n', 
		'\x1D', '\f', '\x1D', '\xE', '\x1D', '\xD2', '\v', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1D', '\x2', '\x2', '\x1E', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', 
		'\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', 
		'\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', 
		'\x3', '\x2', '\t', '\x3', '\x2', '\x32', '\x33', '\x5', '\x2', '\x32', 
		';', '\x43', 'H', '\x63', 'h', '\x3', '\x2', '\x32', ';', '\x6', '\x2', 
		'\f', '\f', '\xF', '\xF', '$', '$', '`', '`', '\x6', '\x2', '\x32', ';', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', 
		'\xF', '\"', '\"', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x2', '\xDB', 
		'\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x3', ';', '\x3', '\x2', '\x2', '\x2', '\x5', '=', '\x3', '\x2', 
		'\x2', '\x2', '\a', '\x42', '\x3', '\x2', '\x2', '\x2', '\t', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'H', '\x3', '\x2', '\x2', '\x2', '\r', 
		'J', '\x3', '\x2', '\x2', '\x2', '\xF', 'N', '\x3', '\x2', '\x2', '\x2', 
		'\x11', 'W', '\x3', '\x2', '\x2', '\x2', '\x13', ']', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x62', '\x3', '\x2', '\x2', '\x2', '\x17', '\x64', '\x3', 
		'\x2', '\x2', '\x2', '\x19', 'u', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '\x8E', '\x3', '\x2', '\x2', '\x2', '!', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '#', '\x93', '\x3', '\x2', '\x2', '\x2', '%', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\'', '\x99', '\x3', '\x2', '\x2', '\x2', 
		')', '\x9C', '\x3', '\x2', '\x2', '\x2', '+', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '-', '\xA0', '\x3', '\x2', '\x2', '\x2', '/', '\xA8', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x33', '\xB5', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\xBF', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\xC4', '\x3', '\x2', '\x2', '\x2', '\x39', '\xCA', '\x3', '\x2', 
		'\x2', '\x2', ';', '<', '\a', '=', '\x2', '\x2', '<', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '=', '>', '\a', 'y', '\x2', '\x2', '>', '?', '\a', '\x63', 
		'\x2', '\x2', '?', '@', '\a', 'k', '\x2', '\x2', '@', '\x41', '\a', 'v', 
		'\x2', '\x2', '\x41', '\x6', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', 
		'\a', '\"', '\x2', '\x2', '\x43', '\b', '\x3', '\x2', '\x2', '\x2', '\x44', 
		'\x45', '\a', 'u', '\x2', '\x2', '\x45', '\x46', '\a', 'g', '\x2', '\x2', 
		'\x46', 'G', '\a', 'v', '\x2', '\x2', 'G', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'H', 'I', '\a', '?', '\x2', '\x2', 'I', '\f', '\x3', '\x2', '\x2', 
		'\x2', 'J', 'K', '\a', 'g', '\x2', '\x2', 'K', 'L', '\a', 'p', '\x2', 
		'\x2', 'L', 'M', '\a', '\x66', '\x2', '\x2', 'M', '\xE', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'O', '\a', '\x65', '\x2', '\x2', 'O', 'P', '\a', 'q', 
		'\x2', '\x2', 'P', 'Q', '\a', 'p', '\x2', '\x2', 'Q', 'R', '\a', 'v', 
		'\x2', '\x2', 'R', 'S', '\a', 'k', '\x2', '\x2', 'S', 'T', '\a', 'p', 
		'\x2', '\x2', 'T', 'U', '\a', 'w', '\x2', '\x2', 'U', 'V', '\a', 'g', 
		'\x2', '\x2', 'V', '\x10', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', 
		'r', '\x2', '\x2', 'X', 'Y', '\a', 't', '\x2', '\x2', 'Y', 'Z', '\a', 
		'k', '\x2', '\x2', 'Z', '[', '\a', 'p', '\x2', '\x2', '[', '\\', '\a', 
		'v', '\x2', '\x2', '\\', '\x12', '\x3', '\x2', '\x2', '\x2', ']', '^', 
		'\a', 'r', '\x2', '\x2', '^', '_', '\a', 'w', '\x2', '\x2', '_', '`', 
		'\a', 'u', '\x2', '\x2', '`', '\x61', '\a', 'j', '\x2', '\x2', '\x61', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\a', '.', '\x2', 
		'\x2', '\x63', '\x16', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', 
		'\x65', '\x2', '\x2', '\x65', '\x66', '\a', 'q', '\x2', '\x2', '\x66', 
		'g', '\a', 'p', '\x2', '\x2', 'g', 'h', '\a', 'p', '\x2', '\x2', 'h', 
		'i', '\a', 'g', '\x2', '\x2', 'i', 'j', '\a', '\x65', '\x2', '\x2', 'j', 
		'k', '\a', 'v', '\x2', '\x2', 'k', 'l', '\a', '\x61', '\x2', '\x2', 'l', 
		'm', '\a', 'm', '\x2', '\x2', 'm', 'n', '\a', 'g', '\x2', '\x2', 'n', 
		'o', '\a', '{', '\x2', '\x2', 'o', 'p', '\a', '\x64', '\x2', '\x2', 'p', 
		'q', '\a', 'q', '\x2', '\x2', 'q', 'r', '\a', '\x63', '\x2', '\x2', 'r', 
		's', '\a', 't', '\x2', '\x2', 's', 't', '\a', '\x66', '\x2', '\x2', 't', 
		'\x18', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '\x65', '\x2', '\x2', 
		'v', 'w', '\a', 'q', '\x2', '\x2', 'w', 'x', '\a', 'p', '\x2', '\x2', 
		'x', 'y', '\a', 'p', '\x2', '\x2', 'y', 'z', '\a', 'g', '\x2', '\x2', 
		'z', '{', '\a', '\x65', '\x2', '\x2', '{', '|', '\a', 'v', '\x2', '\x2', 
		'|', '}', '\a', '\x61', '\x2', '\x2', '}', '~', '\a', 'v', '\x2', '\x2', 
		'~', '\x7F', '\a', 'v', '\x2', '\x2', '\x7F', '\x80', '\a', '{', '\x2', 
		'\x2', '\x80', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\a', 
		'o', '\x2', '\x2', '\x82', '\x83', '\a', 'q', '\x2', '\x2', '\x83', '\x84', 
		'\a', 'w', '\x2', '\x2', '\x84', '\x85', '\a', 'p', '\x2', '\x2', '\x85', 
		'\x86', '\a', 'v', '\x2', '\x2', '\x86', '\x87', '\a', '\x61', '\x2', 
		'\x2', '\x87', '\x88', '\a', '\x66', '\x2', '\x2', '\x88', '\x89', '\a', 
		'k', '\x2', '\x2', '\x89', '\x8A', '\a', 'u', '\x2', '\x2', '\x8A', '\x8B', 
		'\a', 'm', '\x2', '\x2', '\x8B', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8D', '\a', ']', '\x2', '\x2', '\x8D', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', '_', '\x2', '\x2', '\x8F', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x91', '\a', '?', '\x2', '\x2', '\x91', '\x92', 
		'\a', '?', '\x2', '\x2', '\x92', '\"', '\x3', '\x2', '\x2', '\x2', '\x93', 
		'\x94', '\a', '#', '\x2', '\x2', '\x94', '\x95', '\a', '?', '\x2', '\x2', 
		'\x95', '$', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\a', '(', '\x2', 
		'\x2', '\x97', '\x98', '\a', '(', '\x2', '\x2', '\x98', '&', '\x3', '\x2', 
		'\x2', '\x2', '\x99', '\x9A', '\a', '~', '\x2', '\x2', '\x9A', '\x9B', 
		'\a', '~', '\x2', '\x2', '\x9B', '(', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', '*', '\x2', '\x2', '\x9D', '*', '\x3', '\x2', '\x2', '\x2', 
		'\x9E', '\x9F', '\a', '+', '\x2', '\x2', '\x9F', ',', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA1', '\a', '\x32', '\x2', '\x2', '\xA1', '\xA2', '\a', 
		'\x64', '\x2', '\x2', '\xA2', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA5', '\t', '\x2', '\x2', '\x2', '\xA4', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', '\x32', '\x2', 
		'\x2', '\xA9', '\xAA', '\a', 'z', '\x2', '\x2', '\xAA', '\xAC', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAD', '\t', '\x3', '\x2', '\x2', '\xAC', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '\xAE', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\x30', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xB2', '\t', '\x4', '\x2', '\x2', '\xB1', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB9', '\a', '$', '\x2', 
		'\x2', '\xB6', '\xB8', '\n', '\x5', '\x2', '\x2', '\xB7', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\xB8', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBA', '\x3', '\x2', '\x2', 
		'\x2', '\xBA', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB9', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBD', '\a', '$', '\x2', '\x2', '\xBD', 
		'\x34', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xC0', '\t', '\x6', '\x2', 
		'\x2', '\xBF', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC1', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC2', '\x3', '\x2', '\x2', '\x2', '\xC2', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xC5', '\t', '\a', '\x2', '\x2', '\xC4', '\xC3', '\x3', 
		'\x2', '\x2', '\x2', '\xC5', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC6', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\xC7', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC9', '\b', 
		'\x1C', '\x2', '\x2', '\xC9', '\x38', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\xCB', '\a', '\x31', '\x2', '\x2', '\xCB', '\xCC', '\a', '\x31', '\x2', 
		'\x2', '\xCC', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCF', '\n', 
		'\b', '\x2', '\x2', '\xCE', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCF', 
		'\xD2', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xCE', '\x3', '\x2', '\x2', 
		'\x2', '\xD0', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD3', '\x3', 
		'\x2', '\x2', '\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD3', 
		'\xD4', '\b', '\x1D', '\x2', '\x2', '\xD4', ':', '\x3', '\x2', '\x2', 
		'\x2', '\n', '\x2', '\xA6', '\xAE', '\xB3', '\xB9', '\xC1', '\xC6', '\xD0', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace LogiX.Minimal.ActionSequencing
