//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\RichieZ\repos\logix\src\LogiX\Minimal\ActionSequencing\ANTLR\ActionSequence.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LogiX.Minimal.ActionSequencing {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class ActionSequenceParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, BINARY_LITERAL=21, HEX_LITERAL=22, DECIMAL_LITERAL=23, 
		STRING_LITERAL=24, PIN_ID=25, WHITESPACE=26, LINECOMMENT=27;
	public const int
		RULE_program = 0, RULE_actionSequence = 1, RULE_action = 2, RULE_wait = 3, 
		RULE_assignment = 4, RULE_end = 5, RULE_continue = 6, RULE_print = 7, 
		RULE_push = 8, RULE_connectKeyboard = 9, RULE_connectTTY = 10, RULE_exp = 11, 
		RULE_literalexp = 12, RULE_ramexp = 13, RULE_pinexp = 14, RULE_boolexp = 15;
	public static readonly string[] ruleNames = {
		"program", "actionSequence", "action", "wait", "assignment", "end", "continue", 
		"print", "push", "connectKeyboard", "connectTTY", "exp", "literalexp", 
		"ramexp", "pinexp", "boolexp"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'wait'", "' '", "'set'", "'='", "'end'", "'continue'", "'print'", 
		"'push'", "','", "'connect_keyboard'", "'connect_tty'", "'['", "']'", 
		"'=='", "'!='", "'&&'", "'||'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "BINARY_LITERAL", 
		"HEX_LITERAL", "DECIMAL_LITERAL", "STRING_LITERAL", "PIN_ID", "WHITESPACE", 
		"LINECOMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ActionSequence.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ActionSequenceParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ActionSequenceParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ActionSequenceParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionSequenceContext actionSequence() {
			return GetRuleContext<ActionSequenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(ActionSequenceParser.Eof, 0); }
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32;
			actionSequence();
			State = 33;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionSequenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext[] action() {
			return GetRuleContexts<ActionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action(int i) {
			return GetRuleContext<ActionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WHITESPACE() { return GetTokens(ActionSequenceParser.WHITESPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHITESPACE(int i) {
			return GetToken(ActionSequenceParser.WHITESPACE, i);
		}
		public ActionSequenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actionSequence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActionSequence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionSequenceContext actionSequence() {
		ActionSequenceContext _localctx = new ActionSequenceContext(Context, State);
		EnterRule(_localctx, 2, RULE_actionSequence);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 35;
				action();
				State = 39;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==WHITESPACE) {
					{
					{
					State = 36;
					Match(WHITESPACE);
					}
					}
					State = 41;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				}
				State = 44;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__3) | (1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__10) | (1L << T__11))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WaitContext wait() {
			return GetRuleContext<WaitContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EndContext end() {
			return GetRuleContext<EndContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContinueContext @continue() {
			return GetRuleContext<ContinueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintContext print() {
			return GetRuleContext<PrintContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PushContext push() {
			return GetRuleContext<PushContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConnectKeyboardContext connectKeyboard() {
			return GetRuleContext<ConnectKeyboardContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConnectTTYContext connectTTY() {
			return GetRuleContext<ConnectTTYContext>(0);
		}
		public ActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_action; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionContext action() {
		ActionContext _localctx = new ActionContext(Context, State);
		EnterRule(_localctx, 4, RULE_action);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				State = 46;
				assignment();
				}
				break;
			case T__1:
				{
				State = 47;
				wait();
				}
				break;
			case T__5:
				{
				State = 48;
				end();
				}
				break;
			case T__6:
				{
				State = 49;
				@continue();
				}
				break;
			case T__7:
				{
				State = 50;
				print();
				}
				break;
			case T__8:
				{
				State = 51;
				push();
				}
				break;
			case T__10:
				{
				State = 52;
				connectKeyboard();
				}
				break;
			case T__11:
				{
				State = 53;
				connectTTY();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 56;
			Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WaitContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BoolexpContext boolexp() {
			return GetRuleContext<BoolexpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL_LITERAL() { return GetToken(ActionSequenceParser.DECIMAL_LITERAL, 0); }
		public WaitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_wait; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWait(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WaitContext wait() {
		WaitContext _localctx = new WaitContext(Context, State);
		EnterRule(_localctx, 6, RULE_wait);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 58;
			Match(T__1);
			State = 59;
			Match(T__2);
			State = 62;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__18:
			case BINARY_LITERAL:
			case HEX_LITERAL:
			case PIN_ID:
				{
				State = 60;
				boolexp(0);
				}
				break;
			case DECIMAL_LITERAL:
				{
				State = 61;
				Match(DECIMAL_LITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PinexpContext pinexp() {
			return GetRuleContext<PinexpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RamexpContext ramexp() {
			return GetRuleContext<RamexpContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 8, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			Match(T__3);
			State = 65;
			Match(T__2);
			State = 68;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				{
				State = 66;
				pinexp();
				}
				break;
			case 2:
				{
				State = 67;
				ramexp();
				}
				break;
			}
			State = 70;
			Match(T__4);
			State = 71;
			exp();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndContext : ParserRuleContext {
		public EndContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_end; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnd(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EndContext end() {
		EndContext _localctx = new EndContext(Context, State);
		EnterRule(_localctx, 10, RULE_end);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 73;
			Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ContinueContext : ParserRuleContext {
		public ContinueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_continue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContinue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ContinueContext @continue() {
		ContinueContext _localctx = new ContinueContext(Context, State);
		EnterRule(_localctx, 12, RULE_continue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 75;
			Match(T__6);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(ActionSequenceParser.STRING_LITERAL, 0); }
		public PrintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_print; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintContext print() {
		PrintContext _localctx = new PrintContext(Context, State);
		EnterRule(_localctx, 14, RULE_print);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77;
			Match(T__7);
			State = 78;
			Match(T__2);
			State = 79;
			Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PushContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIN_ID() { return GetToken(ActionSequenceParser.PIN_ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BoolexpContext boolexp() {
			return GetRuleContext<BoolexpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL_LITERAL() { return GetToken(ActionSequenceParser.DECIMAL_LITERAL, 0); }
		public PushContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_push; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPush(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PushContext push() {
		PushContext _localctx = new PushContext(Context, State);
		EnterRule(_localctx, 16, RULE_push);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			Match(T__8);
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2) {
				{
				{
				State = 82;
				Match(T__2);
				}
				}
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 88;
			Match(PIN_ID);
			State = 89;
			Match(T__9);
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2) {
				{
				{
				State = 90;
				Match(T__2);
				}
				}
				State = 95;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 98;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__18:
			case BINARY_LITERAL:
			case HEX_LITERAL:
			case PIN_ID:
				{
				State = 96;
				boolexp(0);
				}
				break;
			case DECIMAL_LITERAL:
				{
				State = 97;
				Match(DECIMAL_LITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConnectKeyboardContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIN_ID() { return GetToken(ActionSequenceParser.PIN_ID, 0); }
		public ConnectKeyboardContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_connectKeyboard; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConnectKeyboard(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConnectKeyboardContext connectKeyboard() {
		ConnectKeyboardContext _localctx = new ConnectKeyboardContext(Context, State);
		EnterRule(_localctx, 18, RULE_connectKeyboard);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			Match(T__10);
			State = 104;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2) {
				{
				{
				State = 101;
				Match(T__2);
				}
				}
				State = 106;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 107;
			Match(PIN_ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConnectTTYContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIN_ID() { return GetToken(ActionSequenceParser.PIN_ID, 0); }
		public ConnectTTYContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_connectTTY; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConnectTTY(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConnectTTYContext connectTTY() {
		ConnectTTYContext _localctx = new ConnectTTYContext(Context, State);
		EnterRule(_localctx, 20, RULE_connectTTY);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109;
			Match(T__11);
			State = 113;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2) {
				{
				{
				State = 110;
				Match(T__2);
				}
				}
				State = 115;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 116;
			Match(PIN_ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PinexpContext pinexp() {
			return GetRuleContext<PinexpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RamexpContext ramexp() {
			return GetRuleContext<RamexpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LiteralexpContext literalexp() {
			return GetRuleContext<LiteralexpContext>(0);
		}
		public ExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpContext exp() {
		ExpContext _localctx = new ExpContext(Context, State);
		EnterRule(_localctx, 22, RULE_exp);
		try {
			State = 121;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 118;
				pinexp();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 119;
				ramexp();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 120;
				literalexp();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralexpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BINARY_LITERAL() { return GetToken(ActionSequenceParser.BINARY_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HEX_LITERAL() { return GetToken(ActionSequenceParser.HEX_LITERAL, 0); }
		public LiteralexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literalexp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteralexp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralexpContext literalexp() {
		LiteralexpContext _localctx = new LiteralexpContext(Context, State);
		EnterRule(_localctx, 24, RULE_literalexp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123;
			_la = TokenStream.LA(1);
			if ( !(_la==BINARY_LITERAL || _la==HEX_LITERAL) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RamexpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIN_ID() { return GetToken(ActionSequenceParser.PIN_ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HEX_LITERAL() { return GetToken(ActionSequenceParser.HEX_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BINARY_LITERAL() { return GetToken(ActionSequenceParser.BINARY_LITERAL, 0); }
		public RamexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ramexp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRamexp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RamexpContext ramexp() {
		RamexpContext _localctx = new RamexpContext(Context, State);
		EnterRule(_localctx, 26, RULE_ramexp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125;
			Match(PIN_ID);
			State = 126;
			Match(T__12);
			State = 127;
			_la = TokenStream.LA(1);
			if ( !(_la==BINARY_LITERAL || _la==HEX_LITERAL) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 128;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PinexpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIN_ID() { return GetToken(ActionSequenceParser.PIN_ID, 0); }
		public PinexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pinexp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPinexp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PinexpContext pinexp() {
		PinexpContext _localctx = new PinexpContext(Context, State);
		EnterRule(_localctx, 28, RULE_pinexp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130;
			Match(PIN_ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BoolexpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpContext[] exp() {
			return GetRuleContexts<ExpContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpContext exp(int i) {
			return GetRuleContext<ExpContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BoolexpContext[] boolexp() {
			return GetRuleContexts<BoolexpContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BoolexpContext boolexp(int i) {
			return GetRuleContext<BoolexpContext>(i);
		}
		public BoolexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_boolexp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IActionSequenceVisitor<TResult> typedVisitor = visitor as IActionSequenceVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolexp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BoolexpContext boolexp() {
		return boolexp(0);
	}

	private BoolexpContext boolexp(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BoolexpContext _localctx = new BoolexpContext(Context, _parentState);
		BoolexpContext _prevctx = _localctx;
		int _startState = 30;
		EnterRecursionRule(_localctx, 30, RULE_boolexp, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 145;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				{
				State = 133;
				exp();
				State = 134;
				Match(T__14);
				State = 135;
				exp();
				}
				break;
			case 2:
				{
				State = 137;
				exp();
				State = 138;
				Match(T__15);
				State = 139;
				exp();
				}
				break;
			case 3:
				{
				State = 141;
				Match(T__18);
				State = 142;
				boolexp(0);
				State = 143;
				Match(T__19);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 159;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 157;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
					case 1:
						{
						_localctx = new BoolexpContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_boolexp);
						State = 147;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 148;
						Match(T__2);
						State = 149;
						Match(T__16);
						State = 150;
						Match(T__2);
						State = 151;
						boolexp(4);
						}
						break;
					case 2:
						{
						_localctx = new BoolexpContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_boolexp);
						State = 152;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 153;
						Match(T__2);
						State = 154;
						Match(T__17);
						State = 155;
						Match(T__2);
						State = 156;
						boolexp(3);
						}
						break;
					}
					} 
				}
				State = 161;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 15: return boolexp_sempred((BoolexpContext)_localctx, predIndex);
		}
		return true;
	}
	private bool boolexp_sempred(BoolexpContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		case 1: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x1D', '\xA5', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\a', '\x3', '(', '\n', '\x3', '\f', '\x3', '\xE', 
		'\x3', '+', '\v', '\x3', '\x6', '\x3', '-', '\n', '\x3', '\r', '\x3', 
		'\xE', '\x3', '.', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', 
		'\x39', '\n', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '\x41', '\n', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', 
		'G', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\a', '\n', 'V', '\n', '\n', 
		'\f', '\n', '\xE', '\n', 'Y', '\v', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\a', '\n', '^', '\n', '\n', '\f', '\n', '\xE', '\n', '\x61', '\v', 
		'\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\x65', '\n', '\n', '\x3', 
		'\v', '\x3', '\v', '\a', '\v', 'i', '\n', '\v', '\f', '\v', '\xE', '\v', 
		'l', '\v', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\a', 
		'\f', 'r', '\n', '\f', '\f', '\f', '\xE', '\f', 'u', '\v', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', 
		'|', '\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\x94', '\n', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\a', '\x11', '\xA0', '\n', '\x11', '\f', '\x11', '\xE', '\x11', 
		'\xA3', '\v', '\x11', '\x3', '\x11', '\x2', '\x3', ' ', '\x12', '\x2', 
		'\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', 
		'\x18', '\x1A', '\x1C', '\x1E', ' ', '\x2', '\x3', '\x3', '\x2', '\x17', 
		'\x18', '\x2', '\xAA', '\x2', '\"', '\x3', '\x2', '\x2', '\x2', '\x4', 
		',', '\x3', '\x2', '\x2', '\x2', '\x6', '\x38', '\x3', '\x2', '\x2', '\x2', 
		'\b', '<', '\x3', '\x2', '\x2', '\x2', '\n', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\f', 'K', '\x3', '\x2', '\x2', '\x2', '\xE', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\x10', 'O', '\x3', '\x2', '\x2', '\x2', '\x12', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x14', '\x66', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'o', '\x3', '\x2', '\x2', '\x2', '\x18', '{', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', '}', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x7F', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\x84', '\x3', '\x2', '\x2', '\x2', ' ', '\x93', 
		'\x3', '\x2', '\x2', '\x2', '\"', '#', '\x5', '\x4', '\x3', '\x2', '#', 
		'$', '\a', '\x2', '\x2', '\x3', '$', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'%', ')', '\x5', '\x6', '\x4', '\x2', '&', '(', '\a', '\x1C', '\x2', '\x2', 
		'\'', '&', '\x3', '\x2', '\x2', '\x2', '(', '+', '\x3', '\x2', '\x2', 
		'\x2', ')', '\'', '\x3', '\x2', '\x2', '\x2', ')', '*', '\x3', '\x2', 
		'\x2', '\x2', '*', '-', '\x3', '\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', 
		'\x2', '\x2', ',', '%', '\x3', '\x2', '\x2', '\x2', '-', '.', '\x3', '\x2', 
		'\x2', '\x2', '.', ',', '\x3', '\x2', '\x2', '\x2', '.', '/', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x5', '\x3', '\x2', '\x2', '\x2', '\x30', '\x39', 
		'\x5', '\n', '\x6', '\x2', '\x31', '\x39', '\x5', '\b', '\x5', '\x2', 
		'\x32', '\x39', '\x5', '\f', '\a', '\x2', '\x33', '\x39', '\x5', '\xE', 
		'\b', '\x2', '\x34', '\x39', '\x5', '\x10', '\t', '\x2', '\x35', '\x39', 
		'\x5', '\x12', '\n', '\x2', '\x36', '\x39', '\x5', '\x14', '\v', '\x2', 
		'\x37', '\x39', '\x5', '\x16', '\f', '\x2', '\x38', '\x30', '\x3', '\x2', 
		'\x2', '\x2', '\x38', '\x31', '\x3', '\x2', '\x2', '\x2', '\x38', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\x38', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\x38', '\x34', '\x3', '\x2', '\x2', '\x2', '\x38', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x38', '\x36', '\x3', '\x2', '\x2', '\x2', '\x38', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\x39', ':', '\x3', '\x2', '\x2', '\x2', ':', 
		';', '\a', '\x3', '\x2', '\x2', ';', '\a', '\x3', '\x2', '\x2', '\x2', 
		'<', '=', '\a', '\x4', '\x2', '\x2', '=', '@', '\a', '\x5', '\x2', '\x2', 
		'>', '\x41', '\x5', ' ', '\x11', '\x2', '?', '\x41', '\a', '\x19', '\x2', 
		'\x2', '@', '>', '\x3', '\x2', '\x2', '\x2', '@', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\t', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\a', 
		'\x6', '\x2', '\x2', '\x43', '\x46', '\a', '\x5', '\x2', '\x2', '\x44', 
		'G', '\x5', '\x1E', '\x10', '\x2', '\x45', 'G', '\x5', '\x1C', '\xF', 
		'\x2', '\x46', '\x44', '\x3', '\x2', '\x2', '\x2', '\x46', '\x45', '\x3', 
		'\x2', '\x2', '\x2', 'G', 'H', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', 
		'\a', '\x2', '\x2', 'I', 'J', '\x5', '\x18', '\r', '\x2', 'J', '\v', '\x3', 
		'\x2', '\x2', '\x2', 'K', 'L', '\a', '\b', '\x2', '\x2', 'L', '\r', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'N', '\a', '\t', '\x2', '\x2', 'N', '\xF', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'P', '\a', '\n', '\x2', '\x2', 'P', 'Q', '\a', 
		'\x5', '\x2', '\x2', 'Q', 'R', '\a', '\x1A', '\x2', '\x2', 'R', '\x11', 
		'\x3', '\x2', '\x2', '\x2', 'S', 'W', '\a', '\v', '\x2', '\x2', 'T', 'V', 
		'\a', '\x5', '\x2', '\x2', 'U', 'T', '\x3', '\x2', '\x2', '\x2', 'V', 
		'Y', '\x3', '\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', '\x2', '\x2', 
		'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', '\x1B', '\x2', '\x2', 
		'[', '_', '\a', '\f', '\x2', '\x2', '\\', '^', '\a', '\x5', '\x2', '\x2', 
		']', '\\', '\x3', '\x2', '\x2', '\x2', '^', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x64', '\x3', '\x2', '\x2', '\x2', '\x61', '_', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '\x65', '\x5', ' ', '\x11', '\x2', '\x63', '\x65', 
		'\a', '\x19', '\x2', '\x2', '\x64', '\x62', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\x63', '\x3', '\x2', '\x2', '\x2', '\x65', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x66', 'j', '\a', '\r', '\x2', '\x2', 'g', 'i', '\a', '\x5', 
		'\x2', '\x2', 'h', 'g', '\x3', '\x2', '\x2', '\x2', 'i', 'l', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'h', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x3', '\x2', 
		'\x2', '\x2', 'k', 'm', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', 
		'\x2', '\x2', 'm', 'n', '\a', '\x1B', '\x2', '\x2', 'n', '\x15', '\x3', 
		'\x2', '\x2', '\x2', 'o', 's', '\a', '\xE', '\x2', '\x2', 'p', 'r', '\a', 
		'\x5', '\x2', '\x2', 'q', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 'u', '\x3', 
		'\x2', '\x2', '\x2', 's', 'q', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', 
		'\x2', '\x2', '\x2', 't', 'v', '\x3', '\x2', '\x2', '\x2', 'u', 's', '\x3', 
		'\x2', '\x2', '\x2', 'v', 'w', '\a', '\x1B', '\x2', '\x2', 'w', '\x17', 
		'\x3', '\x2', '\x2', '\x2', 'x', '|', '\x5', '\x1E', '\x10', '\x2', 'y', 
		'|', '\x5', '\x1C', '\xF', '\x2', 'z', '|', '\x5', '\x1A', '\xE', '\x2', 
		'{', 'x', '\x3', '\x2', '\x2', '\x2', '{', 'y', '\x3', '\x2', '\x2', '\x2', 
		'{', 'z', '\x3', '\x2', '\x2', '\x2', '|', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\t', '\x2', '\x2', '\x2', '~', '\x1B', '\x3', '\x2', 
		'\x2', '\x2', '\x7F', '\x80', '\a', '\x1B', '\x2', '\x2', '\x80', '\x81', 
		'\a', '\xF', '\x2', '\x2', '\x81', '\x82', '\t', '\x2', '\x2', '\x2', 
		'\x82', '\x83', '\a', '\x10', '\x2', '\x2', '\x83', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x84', '\x85', '\a', '\x1B', '\x2', '\x2', '\x85', '\x1F', 
		'\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\b', '\x11', '\x1', '\x2', 
		'\x87', '\x88', '\x5', '\x18', '\r', '\x2', '\x88', '\x89', '\a', '\x11', 
		'\x2', '\x2', '\x89', '\x8A', '\x5', '\x18', '\r', '\x2', '\x8A', '\x94', 
		'\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x5', '\x18', '\r', '\x2', 
		'\x8C', '\x8D', '\a', '\x12', '\x2', '\x2', '\x8D', '\x8E', '\x5', '\x18', 
		'\r', '\x2', '\x8E', '\x94', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', 
		'\a', '\x15', '\x2', '\x2', '\x90', '\x91', '\x5', ' ', '\x11', '\x2', 
		'\x91', '\x92', '\a', '\x16', '\x2', '\x2', '\x92', '\x94', '\x3', '\x2', 
		'\x2', '\x2', '\x93', '\x86', '\x3', '\x2', '\x2', '\x2', '\x93', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '\x93', '\x8F', '\x3', '\x2', '\x2', '\x2', 
		'\x94', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\f', '\x5', 
		'\x2', '\x2', '\x96', '\x97', '\a', '\x5', '\x2', '\x2', '\x97', '\x98', 
		'\a', '\x13', '\x2', '\x2', '\x98', '\x99', '\a', '\x5', '\x2', '\x2', 
		'\x99', '\xA0', '\x5', ' ', '\x11', '\x6', '\x9A', '\x9B', '\f', '\x4', 
		'\x2', '\x2', '\x9B', '\x9C', '\a', '\x5', '\x2', '\x2', '\x9C', '\x9D', 
		'\a', '\x14', '\x2', '\x2', '\x9D', '\x9E', '\a', '\x5', '\x2', '\x2', 
		'\x9E', '\xA0', '\x5', ' ', '\x11', '\x5', '\x9F', '\x95', '\x3', '\x2', 
		'\x2', '\x2', '\x9F', '\x9A', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '!', '\x3', '\x2', 
		'\x2', '\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x10', ')', 
		'.', '\x38', '@', '\x46', 'W', '_', '\x64', 'j', 's', '{', '\x93', '\x9F', 
		'\xA1',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace LogiX.Minimal.ActionSequencing
