//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\RichieZ\repos\logix\src\LogiX\Minimal\ActionSequencing\ANTLR\ActionSequence.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LogiX.Minimal.ActionSequencing {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class ActionSequenceLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, BINARY_LITERAL=19, HEX_LITERAL=20, DECIMAL_LITERAL=21, STRING_LITERAL=22, 
		PIN_ID=23, WHITESPACE=24, LINECOMMENT=25;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "BINARY_LITERAL", "HEX_LITERAL", "DECIMAL_LITERAL", "STRING_LITERAL", 
		"PIN_ID", "WHITESPACE", "LINECOMMENT"
	};


	public ActionSequenceLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ActionSequenceLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'wait'", "' '", "'set'", "'='", "'end'", "'continue'", "'print'", 
		"'push'", "','", "'['", "']'", "'=='", "'!='", "'&&'", "'||'", "'('", 
		"')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, "BINARY_LITERAL", "HEX_LITERAL", 
		"DECIMAL_LITERAL", "STRING_LITERAL", "PIN_ID", "WHITESPACE", "LINECOMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ActionSequence.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ActionSequenceLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1B', '\xA7', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x6', '\x14', 'w', '\n', '\x14', '\r', '\x14', 
		'\xE', '\x14', 'x', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x6', '\x15', '\x7F', '\n', '\x15', '\r', '\x15', '\xE', '\x15', 
		'\x80', '\x3', '\x16', '\x6', '\x16', '\x84', '\n', '\x16', '\r', '\x16', 
		'\xE', '\x16', '\x85', '\x3', '\x17', '\x3', '\x17', '\a', '\x17', '\x8A', 
		'\n', '\x17', '\f', '\x17', '\xE', '\x17', '\x8D', '\v', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x18', '\x6', '\x18', '\x92', '\n', '\x18', 
		'\r', '\x18', '\xE', '\x18', '\x93', '\x3', '\x19', '\x6', '\x19', '\x97', 
		'\n', '\x19', '\r', '\x19', '\xE', '\x19', '\x98', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\a', 
		'\x1A', '\xA1', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\xA4', '\v', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x2', '\x2', '\x1B', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x3', '\x2', '\t', '\x3', 
		'\x2', '\x32', '\x33', '\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 
		'h', '\x3', '\x2', '\x32', ';', '\x6', '\x2', '\f', '\f', '\xF', '\xF', 
		'$', '$', '`', '`', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', 
		'\x2', '\f', '\f', '\xF', '\xF', '\x2', '\xAD', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x3', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\a', '<', '\x3', '\x2', '\x2', '\x2', '\t', '>', '\x3', '\x2', '\x2', 
		'\x2', '\v', '\x42', '\x3', '\x2', '\x2', '\x2', '\r', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\xF', 'H', '\x3', '\x2', '\x2', '\x2', '\x11', 'Q', 
		'\x3', '\x2', '\x2', '\x2', '\x13', 'W', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\\', '\x3', '\x2', '\x2', '\x2', '\x17', '^', '\x3', '\x2', '\x2', '\x2', 
		'\x19', '`', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x62', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\x65', '\x3', '\x2', '\x2', '\x2', '\x1F', 'h', 
		'\x3', '\x2', '\x2', '\x2', '!', 'k', '\x3', '\x2', '\x2', '\x2', '#', 
		'n', '\x3', '\x2', '\x2', '\x2', '%', 'p', '\x3', '\x2', '\x2', '\x2', 
		'\'', 'r', '\x3', '\x2', '\x2', '\x2', ')', 'z', '\x3', '\x2', '\x2', 
		'\x2', '+', '\x83', '\x3', '\x2', '\x2', '\x2', '-', '\x87', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x91', '\x3', '\x2', '\x2', '\x2', '\x31', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\x9C', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x36', '\a', '=', '\x2', '\x2', '\x36', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\x38', '\a', 'y', '\x2', '\x2', '\x38', '\x39', 
		'\a', '\x63', '\x2', '\x2', '\x39', ':', '\a', 'k', '\x2', '\x2', ':', 
		';', '\a', 'v', '\x2', '\x2', ';', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'<', '=', '\a', '\"', '\x2', '\x2', '=', '\b', '\x3', '\x2', '\x2', '\x2', 
		'>', '?', '\a', 'u', '\x2', '\x2', '?', '@', '\a', 'g', '\x2', '\x2', 
		'@', '\x41', '\a', 'v', '\x2', '\x2', '\x41', '\n', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '\x43', '\a', '?', '\x2', '\x2', '\x43', '\f', '\x3', '\x2', 
		'\x2', '\x2', '\x44', '\x45', '\a', 'g', '\x2', '\x2', '\x45', '\x46', 
		'\a', 'p', '\x2', '\x2', '\x46', 'G', '\a', '\x66', '\x2', '\x2', 'G', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', '\x65', '\x2', '\x2', 
		'I', 'J', '\a', 'q', '\x2', '\x2', 'J', 'K', '\a', 'p', '\x2', '\x2', 
		'K', 'L', '\a', 'v', '\x2', '\x2', 'L', 'M', '\a', 'k', '\x2', '\x2', 
		'M', 'N', '\a', 'p', '\x2', '\x2', 'N', 'O', '\a', 'w', '\x2', '\x2', 
		'O', 'P', '\a', 'g', '\x2', '\x2', 'P', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\a', 'r', '\x2', '\x2', 'R', 'S', '\a', 't', '\x2', '\x2', 
		'S', 'T', '\a', 'k', '\x2', '\x2', 'T', 'U', '\a', 'p', '\x2', '\x2', 
		'U', 'V', '\a', 'v', '\x2', '\x2', 'V', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'W', 'X', '\a', 'r', '\x2', '\x2', 'X', 'Y', '\a', 'w', '\x2', '\x2', 
		'Y', 'Z', '\a', 'u', '\x2', '\x2', 'Z', '[', '\a', 'j', '\x2', '\x2', 
		'[', '\x14', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\a', '.', '\x2', 
		'\x2', ']', '\x16', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', ']', '\x2', 
		'\x2', '_', '\x18', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', '_', 
		'\x2', '\x2', '\x61', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\a', '?', '\x2', '\x2', '\x63', '\x64', '\a', '?', '\x2', '\x2', '\x64', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', '#', '\x2', 
		'\x2', '\x66', 'g', '\a', '?', '\x2', '\x2', 'g', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', 'h', 'i', '\a', '(', '\x2', '\x2', 'i', 'j', '\a', '(', 
		'\x2', '\x2', 'j', ' ', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', '~', 
		'\x2', '\x2', 'l', 'm', '\a', '~', '\x2', '\x2', 'm', '\"', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'o', '\a', '*', '\x2', '\x2', 'o', '$', '\x3', '\x2', 
		'\x2', '\x2', 'p', 'q', '\a', '+', '\x2', '\x2', 'q', '&', '\x3', '\x2', 
		'\x2', '\x2', 'r', 's', '\a', '\x32', '\x2', '\x2', 's', 't', '\a', '\x64', 
		'\x2', '\x2', 't', 'v', '\x3', '\x2', '\x2', '\x2', 'u', 'w', '\t', '\x2', 
		'\x2', '\x2', 'v', 'u', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', '\x2', 
		'\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\x3', '\x2', 
		'\x2', '\x2', 'y', '(', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '\x32', 
		'\x2', '\x2', '{', '|', '\a', 'z', '\x2', '\x2', '|', '~', '\x3', '\x2', 
		'\x2', '\x2', '}', '\x7F', '\t', '\x3', '\x2', '\x2', '~', '}', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '*', '\x3', '\x2', '\x2', '\x2', '\x82', '\x84', '\t', 
		'\x4', '\x2', '\x2', '\x83', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x85', '\x3', '\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x86', ',', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x8B', '\a', '$', '\x2', '\x2', '\x88', 
		'\x8A', '\n', '\x5', '\x2', '\x2', '\x89', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x89', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', '$', '\x2', '\x2', '\x8F', '.', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x92', '\t', '\x6', '\x2', '\x2', '\x91', '\x90', 
		'\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\x3', '\x2', 
		'\x2', '\x2', '\x94', '\x30', '\x3', '\x2', '\x2', '\x2', '\x95', '\x97', 
		'\t', '\a', '\x2', '\x2', '\x96', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x97', '\x98', '\x3', '\x2', '\x2', '\x2', '\x98', '\x96', '\x3', '\x2', 
		'\x2', '\x2', '\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', 
		'\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\b', '\x19', '\x2', '\x2', 
		'\x9B', '\x32', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', '\a', '\x31', 
		'\x2', '\x2', '\x9D', '\x9E', '\a', '\x31', '\x2', '\x2', '\x9E', '\xA2', 
		'\x3', '\x2', '\x2', '\x2', '\x9F', '\xA1', '\n', '\b', '\x2', '\x2', 
		'\xA0', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA3', '\xA5', '\x3', '\x2', '\x2', '\x2', 
		'\xA4', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\b', '\x1A', 
		'\x2', '\x2', '\xA6', '\x34', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', 
		'x', '\x80', '\x85', '\x8B', '\x93', '\x98', '\xA2', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace LogiX.Minimal.ActionSequencing
