//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\RichieZ\repos\logix\src\LogiX\Minimal\ActionSequencing\ANTLR\ActionSequence.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LogiX.Minimal.ActionSequencing {
#pragma warning disable 3021
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class ActionSequenceLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, BINARY_LITERAL=23, HEX_LITERAL=24, 
		DECIMAL_LITERAL=25, STRING_LITERAL=26, PIN_ID=27, WHITESPACE=28, LINECOMMENT=29;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "T__18", "T__19", "T__20", "T__21", "BINARY_LITERAL", "HEX_LITERAL", 
		"DECIMAL_LITERAL", "STRING_LITERAL", "PIN_ID", "WHITESPACE", "LINECOMMENT"
	};


	public ActionSequenceLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ActionSequenceLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'ext'", "'wait'", "'set'", "'='", "'end'", "'continue'", 
		"'print'", "'push'", "','", "'connect_keyboard'", "'connect_tty'", "'mount_disk'", 
		"'connect_ledmatrix'", "'['", "']'", "'=='", "'!='", "'&&'", "'||'", "'('", 
		"')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, "BINARY_LITERAL", 
		"HEX_LITERAL", "DECIMAL_LITERAL", "STRING_LITERAL", "PIN_ID", "WHITESPACE", 
		"LINECOMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ActionSequence.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ActionSequenceLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1F', '\xEB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x6', '\x18', '\xBB', '\n', '\x18', 
		'\r', '\x18', '\xE', '\x18', '\xBC', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x6', '\x19', '\xC3', '\n', '\x19', '\r', '\x19', 
		'\xE', '\x19', '\xC4', '\x3', '\x1A', '\x6', '\x1A', '\xC8', '\n', '\x1A', 
		'\r', '\x1A', '\xE', '\x1A', '\xC9', '\x3', '\x1B', '\x3', '\x1B', '\a', 
		'\x1B', '\xCE', '\n', '\x1B', '\f', '\x1B', '\xE', '\x1B', '\xD1', '\v', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x6', '\x1C', '\xD6', 
		'\n', '\x1C', '\r', '\x1C', '\xE', '\x1C', '\xD7', '\x3', '\x1D', '\x6', 
		'\x1D', '\xDB', '\n', '\x1D', '\r', '\x1D', '\xE', '\x1D', '\xDC', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\a', '\x1E', '\xE5', '\n', '\x1E', '\f', '\x1E', '\xE', '\x1E', 
		'\xE8', '\v', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x2', '\x2', '\x1F', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', 
		'#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', 
		'\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', 
		'\x1D', '\x39', '\x1E', ';', '\x1F', '\x3', '\x2', '\t', '\x3', '\x2', 
		'\x32', '\x33', '\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', '\x3', 
		'\x2', '\x32', ';', '\x6', '\x2', '\f', '\f', '\xF', '\xF', '$', '$', 
		'`', '`', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', 
		'|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', '\x2', 
		'\f', '\f', '\xF', '\xF', '\x2', '\xF1', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '=', '\x3', '\x2', '\x2', '\x2', '\x5', '?', '\x3', '\x2', '\x2', 
		'\x2', '\a', '\x43', '\x3', '\x2', '\x2', '\x2', '\t', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\v', 'L', '\x3', '\x2', '\x2', '\x2', '\r', 'N', '\x3', 
		'\x2', '\x2', '\x2', '\xF', 'R', '\x3', '\x2', '\x2', '\x2', '\x11', '[', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\x61', '\x3', '\x2', '\x2', '\x2', 
		'\x15', '\x66', '\x3', '\x2', '\x2', '\x2', '\x17', 'h', '\x3', '\x2', 
		'\x2', '\x2', '\x19', 'y', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\x90', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\xA2', '\x3', '\x2', '\x2', '\x2', '!', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '#', '\xA6', '\x3', '\x2', '\x2', '\x2', '%', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\'', '\xAC', '\x3', '\x2', '\x2', '\x2', ')', '\xAF', 
		'\x3', '\x2', '\x2', '\x2', '+', '\xB2', '\x3', '\x2', '\x2', '\x2', '-', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '/', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\xBE', '\x3', '\x2', '\x2', '\x2', '\x33', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\xCB', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\xD5', '\x3', '\x2', '\x2', '\x2', '\x39', '\xDA', '\x3', '\x2', '\x2', 
		'\x2', ';', '\xE0', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '=', '\x2', 
		'\x2', '>', '\x4', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', 'g', '\x2', 
		'\x2', '@', '\x41', '\a', 'z', '\x2', '\x2', '\x41', '\x42', '\a', 'v', 
		'\x2', '\x2', '\x42', '\x6', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', 
		'\a', 'y', '\x2', '\x2', '\x44', '\x45', '\a', '\x63', '\x2', '\x2', '\x45', 
		'\x46', '\a', 'k', '\x2', '\x2', '\x46', 'G', '\a', 'v', '\x2', '\x2', 
		'G', '\b', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', 'u', '\x2', '\x2', 
		'I', 'J', '\a', 'g', '\x2', '\x2', 'J', 'K', '\a', 'v', '\x2', '\x2', 
		'K', '\n', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', '?', '\x2', '\x2', 
		'M', '\f', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\a', 'g', '\x2', '\x2', 
		'O', 'P', '\a', 'p', '\x2', '\x2', 'P', 'Q', '\a', '\x66', '\x2', '\x2', 
		'Q', '\xE', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\a', '\x65', '\x2', 
		'\x2', 'S', 'T', '\a', 'q', '\x2', '\x2', 'T', 'U', '\a', 'p', '\x2', 
		'\x2', 'U', 'V', '\a', 'v', '\x2', '\x2', 'V', 'W', '\a', 'k', '\x2', 
		'\x2', 'W', 'X', '\a', 'p', '\x2', '\x2', 'X', 'Y', '\a', 'w', '\x2', 
		'\x2', 'Y', 'Z', '\a', 'g', '\x2', '\x2', 'Z', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\a', 'r', '\x2', '\x2', '\\', ']', '\a', 't', '\x2', 
		'\x2', ']', '^', '\a', 'k', '\x2', '\x2', '^', '_', '\a', 'p', '\x2', 
		'\x2', '_', '`', '\a', 'v', '\x2', '\x2', '`', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '\x62', '\a', 'r', '\x2', '\x2', '\x62', '\x63', '\a', 
		'w', '\x2', '\x2', '\x63', '\x64', '\a', 'u', '\x2', '\x2', '\x64', '\x65', 
		'\a', 'j', '\x2', '\x2', '\x65', '\x14', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'g', '\a', '.', '\x2', '\x2', 'g', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'h', 'i', '\a', '\x65', '\x2', '\x2', 'i', 'j', '\a', 'q', '\x2', '\x2', 
		'j', 'k', '\a', 'p', '\x2', '\x2', 'k', 'l', '\a', 'p', '\x2', '\x2', 
		'l', 'm', '\a', 'g', '\x2', '\x2', 'm', 'n', '\a', '\x65', '\x2', '\x2', 
		'n', 'o', '\a', 'v', '\x2', '\x2', 'o', 'p', '\a', '\x61', '\x2', '\x2', 
		'p', 'q', '\a', 'm', '\x2', '\x2', 'q', 'r', '\a', 'g', '\x2', '\x2', 
		'r', 's', '\a', '{', '\x2', '\x2', 's', 't', '\a', '\x64', '\x2', '\x2', 
		't', 'u', '\a', 'q', '\x2', '\x2', 'u', 'v', '\a', '\x63', '\x2', '\x2', 
		'v', 'w', '\a', 't', '\x2', '\x2', 'w', 'x', '\a', '\x66', '\x2', '\x2', 
		'x', '\x18', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '\x65', '\x2', 
		'\x2', 'z', '{', '\a', 'q', '\x2', '\x2', '{', '|', '\a', 'p', '\x2', 
		'\x2', '|', '}', '\a', 'p', '\x2', '\x2', '}', '~', '\a', 'g', '\x2', 
		'\x2', '~', '\x7F', '\a', '\x65', '\x2', '\x2', '\x7F', '\x80', '\a', 
		'v', '\x2', '\x2', '\x80', '\x81', '\a', '\x61', '\x2', '\x2', '\x81', 
		'\x82', '\a', 'v', '\x2', '\x2', '\x82', '\x83', '\a', 'v', '\x2', '\x2', 
		'\x83', '\x84', '\a', '{', '\x2', '\x2', '\x84', '\x1A', '\x3', '\x2', 
		'\x2', '\x2', '\x85', '\x86', '\a', 'o', '\x2', '\x2', '\x86', '\x87', 
		'\a', 'q', '\x2', '\x2', '\x87', '\x88', '\a', 'w', '\x2', '\x2', '\x88', 
		'\x89', '\a', 'p', '\x2', '\x2', '\x89', '\x8A', '\a', 'v', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', '\x61', '\x2', '\x2', '\x8B', '\x8C', '\a', '\x66', 
		'\x2', '\x2', '\x8C', '\x8D', '\a', 'k', '\x2', '\x2', '\x8D', '\x8E', 
		'\a', 'u', '\x2', '\x2', '\x8E', '\x8F', '\a', 'm', '\x2', '\x2', '\x8F', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\a', '\x65', '\x2', 
		'\x2', '\x91', '\x92', '\a', 'q', '\x2', '\x2', '\x92', '\x93', '\a', 
		'p', '\x2', '\x2', '\x93', '\x94', '\a', 'p', '\x2', '\x2', '\x94', '\x95', 
		'\a', 'g', '\x2', '\x2', '\x95', '\x96', '\a', '\x65', '\x2', '\x2', '\x96', 
		'\x97', '\a', 'v', '\x2', '\x2', '\x97', '\x98', '\a', '\x61', '\x2', 
		'\x2', '\x98', '\x99', '\a', 'n', '\x2', '\x2', '\x99', '\x9A', '\a', 
		'g', '\x2', '\x2', '\x9A', '\x9B', '\a', '\x66', '\x2', '\x2', '\x9B', 
		'\x9C', '\a', 'o', '\x2', '\x2', '\x9C', '\x9D', '\a', '\x63', '\x2', 
		'\x2', '\x9D', '\x9E', '\a', 'v', '\x2', '\x2', '\x9E', '\x9F', '\a', 
		't', '\x2', '\x2', '\x9F', '\xA0', '\a', 'k', '\x2', '\x2', '\xA0', '\xA1', 
		'\a', 'z', '\x2', '\x2', '\xA1', '\x1E', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA3', '\a', ']', '\x2', '\x2', '\xA3', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\xA4', '\xA5', '\a', '_', '\x2', '\x2', '\xA5', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA7', '\a', '?', '\x2', '\x2', '\xA7', '\xA8', '\a', 
		'?', '\x2', '\x2', '\xA8', '$', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', 
		'\a', '#', '\x2', '\x2', '\xAA', '\xAB', '\a', '?', '\x2', '\x2', '\xAB', 
		'&', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\a', '(', '\x2', '\x2', 
		'\xAD', '\xAE', '\a', '(', '\x2', '\x2', '\xAE', '(', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB0', '\a', '~', '\x2', '\x2', '\xB0', '\xB1', '\a', 
		'~', '\x2', '\x2', '\xB1', '*', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', 
		'\a', '*', '\x2', '\x2', '\xB3', ',', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB5', '\a', '+', '\x2', '\x2', '\xB5', '.', '\x3', '\x2', '\x2', '\x2', 
		'\xB6', '\xB7', '\a', '\x32', '\x2', '\x2', '\xB7', '\xB8', '\a', '\x64', 
		'\x2', '\x2', '\xB8', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBB', 
		'\t', '\x2', '\x2', '\x2', '\xBA', '\xB9', '\x3', '\x2', '\x2', '\x2', 
		'\xBB', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBA', '\x3', '\x2', 
		'\x2', '\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBD', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\a', '\x32', '\x2', '\x2', 
		'\xBF', '\xC0', '\a', 'z', '\x2', '\x2', '\xC0', '\xC2', '\x3', '\x2', 
		'\x2', '\x2', '\xC1', '\xC3', '\t', '\x3', '\x2', '\x2', '\xC2', '\xC1', 
		'\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', '\x2', '\x2', '\x2', 
		'\xC4', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', '\x3', '\x2', 
		'\x2', '\x2', '\xC5', '\x32', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC8', 
		'\t', '\x4', '\x2', '\x2', '\xC7', '\xC6', '\x3', '\x2', '\x2', '\x2', 
		'\xC8', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC7', '\x3', '\x2', 
		'\x2', '\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCA', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\xCB', '\xCF', '\a', '$', '\x2', '\x2', '\xCC', 
		'\xCE', '\n', '\x5', '\x2', '\x2', '\xCD', '\xCC', '\x3', '\x2', '\x2', 
		'\x2', '\xCE', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '\xCF', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD0', 
		'\xD2', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCF', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '\xD3', '\a', '$', '\x2', '\x2', '\xD3', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD6', '\t', '\x6', '\x2', '\x2', '\xD5', 
		'\xD4', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\x3', '\x2', '\x2', 
		'\x2', '\xD7', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', 
		'\x2', '\x2', '\x2', '\xD8', '\x38', '\x3', '\x2', '\x2', '\x2', '\xD9', 
		'\xDB', '\t', '\a', '\x2', '\x2', '\xDA', '\xD9', '\x3', '\x2', '\x2', 
		'\x2', '\xDB', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDA', '\x3', 
		'\x2', '\x2', '\x2', '\xDC', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDD', 
		'\xDE', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xDF', '\b', '\x1D', '\x2', 
		'\x2', '\xDF', ':', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\a', 
		'\x31', '\x2', '\x2', '\xE1', '\xE2', '\a', '\x31', '\x2', '\x2', '\xE2', 
		'\xE6', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE5', '\n', '\b', '\x2', 
		'\x2', '\xE4', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE8', '\x3', 
		'\x2', '\x2', '\x2', '\xE6', '\xE4', '\x3', '\x2', '\x2', '\x2', '\xE6', 
		'\xE7', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE9', '\x3', '\x2', '\x2', 
		'\x2', '\xE8', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEA', '\b', 
		'\x1E', '\x2', '\x2', '\xEA', '<', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', 
		'\xBC', '\xC4', '\xC9', '\xCF', '\xD7', '\xDC', '\xE6', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace LogiX.Minimal.ActionSequencing
