//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/dcronqvist/repos/logix/assets/plugins/flisp-plugin/code/FLISPC/FLISPC.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FLISPCParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IFLISPCVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] FLISPCParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncdef([NotNull] FLISPCParser.FuncdefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] FLISPCParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] FLISPCParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.whilestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhilestatement([NotNull] FLISPCParser.WhilestatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.ifstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfstatement([NotNull] FLISPCParser.IfstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.paramlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamlist([NotNull] FLISPCParser.ParamlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.funccall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunccall([NotNull] FLISPCParser.FunccallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArglist([NotNull] FLISPCParser.ArglistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] FLISPCParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] FLISPCParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] FLISPCParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FLISPCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] FLISPCParser.ExprContext context);
}
