//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/dcronqvist/repos/logix/examples/d1/d1-plugin/code/D1Assembly/D1Assembly.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace D1Plugin.D1Assembly {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="D1AssemblyParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ID1AssemblyVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="D1AssemblyParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] D1AssemblyParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D1AssemblyParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] D1AssemblyParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D1AssemblyParser.instrline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstrline([NotNull] D1AssemblyParser.InstrlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D1AssemblyParser.symbolline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbolline([NotNull] D1AssemblyParser.SymbollineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D1AssemblyParser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbol([NotNull] D1AssemblyParser.SymbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D1AssemblyParser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArglist([NotNull] D1AssemblyParser.ArglistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D1AssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] D1AssemblyParser.ArgumentContext context);
}
} // namespace D1Plugin.D1Assembly
