//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Daniel\winrepos\logix\examples\d2\d2-plugin\code\D2C\D2C.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class D2CLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BOR=1, BXOR=2, PLUS=3, INCREMENT=4, DECREMENT=5, MINUS=6, STAR=7, HASH=8, 
		AMPERSAND=9, DIV=10, EQ=11, EQEQ=12, NEQ=13, LESSTHAN=14, GREATHAN=15, 
		COMMA=16, SEMI=17, LPAREN=18, RPAREN=19, LCURLY=20, RCURLY=21, IF=22, 
		ELSE=23, ELSEIF=24, RETURN=25, FOR=26, WHILE=27, BREAK=28, DEFINE=29, 
		ORG=30, DECIMALLIT=31, HEXADECILIT=32, BINARYLIT=33, STRINGLIT=34, COMMENT=35, 
		ID=36, WS=37;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"BOR", "BXOR", "PLUS", "INCREMENT", "DECREMENT", "MINUS", "STAR", "HASH", 
		"AMPERSAND", "DIV", "EQ", "EQEQ", "NEQ", "LESSTHAN", "GREATHAN", "COMMA", 
		"SEMI", "LPAREN", "RPAREN", "LCURLY", "RCURLY", "IF", "ELSE", "ELSEIF", 
		"RETURN", "FOR", "WHILE", "BREAK", "DEFINE", "ORG", "DECIMALLIT", "HEXADECILIT", 
		"BINARYLIT", "STRINGLIT", "COMMENT", "ID", "WS", "ESC", "SAFECODEPOINT"
	};


	public D2CLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public D2CLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'|'", "'^'", "'+'", "'++'", "'--'", "'-'", "'*'", "'#'", "'&'", 
		"'/'", "'='", "'=='", "'!='", "'<'", "'>'", "','", "';'", "'('", "')'", 
		"'{'", "'}'", "'if'", "'else'", "'elseif'", "'return'", "'for'", "'while'", 
		"'break'", "'define'", "'org'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BOR", "BXOR", "PLUS", "INCREMENT", "DECREMENT", "MINUS", "STAR", 
		"HASH", "AMPERSAND", "DIV", "EQ", "EQEQ", "NEQ", "LESSTHAN", "GREATHAN", 
		"COMMA", "SEMI", "LPAREN", "RPAREN", "LCURLY", "RCURLY", "IF", "ELSE", 
		"ELSEIF", "RETURN", "FOR", "WHILE", "BREAK", "DEFINE", "ORG", "DECIMALLIT", 
		"HEXADECILIT", "BINARYLIT", "STRINGLIT", "COMMENT", "ID", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "D2C.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static D2CLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\'', '\xED', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x6', ' ', '\xB2', 
		'\n', ' ', '\r', ' ', '\xE', ' ', '\xB3', '\x3', '!', '\x3', '!', '\x3', 
		'!', '\x3', '!', '\x6', '!', '\xBA', '\n', '!', '\r', '!', '\xE', '!', 
		'\xBB', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x6', '\"', 
		'\xC2', '\n', '\"', '\r', '\"', '\xE', '\"', '\xC3', '\x3', '#', '\x3', 
		'#', '\x3', '#', '\a', '#', '\xC9', '\n', '#', '\f', '#', '\xE', '#', 
		'\xCC', '\v', '#', '\x3', '#', '\x3', '#', '\x3', '$', '\x3', '$', '\x3', 
		'$', '\x3', '$', '\a', '$', '\xD4', '\n', '$', '\f', '$', '\xE', '$', 
		'\xD7', '\v', '$', '\x3', '$', '\x3', '$', '\x3', '%', '\x3', '%', '\a', 
		'%', '\xDD', '\n', '%', '\f', '%', '\xE', '%', '\xE0', '\v', '%', '\x3', 
		'&', '\x6', '&', '\xE3', '\n', '&', '\r', '&', '\xE', '&', '\xE4', '\x3', 
		'&', '\x3', '&', '\x3', '\'', '\x3', '\'', '\x3', '\'', '\x3', '(', '\x3', 
		'(', '\x2', '\x2', ')', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', 
		'\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', 
		'\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', 
		'\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', 
		'\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', 
		' ', '?', '!', '\x41', '\"', '\x43', '#', '\x45', '$', 'G', '%', 'I', 
		'&', 'K', '\'', 'M', '\x2', 'O', '\x2', '\x3', '\x2', '\v', '\x3', '\x2', 
		'\x32', ';', '\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', '\x3', 
		'\x2', '\x32', '\x33', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x5', 
		'\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', 
		';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x5', '\x2', '\v', '\f', 
		'\xE', '\xF', '\"', '\"', '\n', '\x2', '$', '$', '\x31', '\x31', '^', 
		'^', '\x64', '\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 'v', '\x5', '\x2', 
		'\x2', '!', '$', '$', '^', '^', '\x2', '\xF2', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x3', 'Q', '\x3', '\x2', 
		'\x2', '\x2', '\x5', 'S', '\x3', '\x2', '\x2', '\x2', '\a', 'U', '\x3', 
		'\x2', '\x2', '\x2', '\t', 'W', '\x3', '\x2', '\x2', '\x2', '\v', 'Z', 
		'\x3', '\x2', '\x2', '\x2', '\r', ']', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'_', '\x3', '\x2', '\x2', '\x2', '\x11', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '\x63', '\x3', '\x2', '\x2', '\x2', '\x15', '\x65', '\x3', 
		'\x2', '\x2', '\x2', '\x17', 'g', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'i', '\x3', '\x2', '\x2', '\x2', '\x1B', 'l', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', 'o', '\x3', '\x2', '\x2', '\x2', '\x1F', 'q', '\x3', '\x2', '\x2', 
		'\x2', '!', 's', '\x3', '\x2', '\x2', '\x2', '#', 'u', '\x3', '\x2', '\x2', 
		'\x2', '%', 'w', '\x3', '\x2', '\x2', '\x2', '\'', 'y', '\x3', '\x2', 
		'\x2', '\x2', ')', '{', '\x3', '\x2', '\x2', '\x2', '+', '}', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x7F', '\x3', '\x2', '\x2', '\x2', '/', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x87', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x35', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x37', '\x99', '\x3', '\x2', '\x2', '\x2', '\x39', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', ';', '\xA5', '\x3', '\x2', '\x2', '\x2', '=', '\xAC', 
		'\x3', '\x2', '\x2', '\x2', '?', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\x43', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\xC5', '\x3', '\x2', '\x2', '\x2', 'G', '\xCF', '\x3', 
		'\x2', '\x2', '\x2', 'I', '\xDA', '\x3', '\x2', '\x2', '\x2', 'K', '\xE2', 
		'\x3', '\x2', '\x2', '\x2', 'M', '\xE8', '\x3', '\x2', '\x2', '\x2', 'O', 
		'\xEB', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\a', '~', '\x2', '\x2', 
		'R', '\x4', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '`', '\x2', '\x2', 
		'T', '\x6', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '-', '\x2', '\x2', 
		'V', '\b', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', '-', '\x2', '\x2', 
		'X', 'Y', '\a', '-', '\x2', '\x2', 'Y', '\n', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\a', '/', '\x2', '\x2', '[', '\\', '\a', '/', '\x2', '\x2', 
		'\\', '\f', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '/', '\x2', '\x2', 
		'^', '\xE', '\x3', '\x2', '\x2', '\x2', '_', '`', '\a', ',', '\x2', '\x2', 
		'`', '\x10', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\a', '%', '\x2', 
		'\x2', '\x62', '\x12', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\a', 
		'(', '\x2', '\x2', '\x64', '\x14', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x66', '\a', '\x31', '\x2', '\x2', '\x66', '\x16', '\x3', '\x2', '\x2', 
		'\x2', 'g', 'h', '\a', '?', '\x2', '\x2', 'h', '\x18', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'j', '\a', '?', '\x2', '\x2', 'j', 'k', '\a', '?', '\x2', 
		'\x2', 'k', '\x1A', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '#', '\x2', 
		'\x2', 'm', 'n', '\a', '?', '\x2', '\x2', 'n', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'p', '\a', '>', '\x2', '\x2', 'p', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\a', '@', '\x2', '\x2', 'r', ' ', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\a', '.', '\x2', '\x2', 't', '\"', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'v', '\a', '=', '\x2', '\x2', 'v', '$', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\a', '*', '\x2', '\x2', 'x', '&', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'z', '\a', '+', '\x2', '\x2', 'z', '(', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\a', '}', '\x2', '\x2', '|', '*', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\a', '\x7F', '\x2', '\x2', '~', ',', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x80', '\a', 'k', '\x2', '\x2', '\x80', '\x81', '\a', 
		'h', '\x2', '\x2', '\x81', '.', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', 
		'\a', 'g', '\x2', '\x2', '\x83', '\x84', '\a', 'n', '\x2', '\x2', '\x84', 
		'\x85', '\a', 'u', '\x2', '\x2', '\x85', '\x86', '\a', 'g', '\x2', '\x2', 
		'\x86', '\x30', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\a', 'g', 
		'\x2', '\x2', '\x88', '\x89', '\a', 'n', '\x2', '\x2', '\x89', '\x8A', 
		'\a', 'u', '\x2', '\x2', '\x8A', '\x8B', '\a', 'g', '\x2', '\x2', '\x8B', 
		'\x8C', '\a', 'k', '\x2', '\x2', '\x8C', '\x8D', '\a', 'h', '\x2', '\x2', 
		'\x8D', '\x32', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', 't', 
		'\x2', '\x2', '\x8F', '\x90', '\a', 'g', '\x2', '\x2', '\x90', '\x91', 
		'\a', 'v', '\x2', '\x2', '\x91', '\x92', '\a', 'w', '\x2', '\x2', '\x92', 
		'\x93', '\a', 't', '\x2', '\x2', '\x93', '\x94', '\a', 'p', '\x2', '\x2', 
		'\x94', '\x34', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\a', 'h', 
		'\x2', '\x2', '\x96', '\x97', '\a', 'q', '\x2', '\x2', '\x97', '\x98', 
		'\a', 't', '\x2', '\x2', '\x98', '\x36', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x9A', '\a', 'y', '\x2', '\x2', '\x9A', '\x9B', '\a', 'j', '\x2', '\x2', 
		'\x9B', '\x9C', '\a', 'k', '\x2', '\x2', '\x9C', '\x9D', '\a', 'n', '\x2', 
		'\x2', '\x9D', '\x9E', '\a', 'g', '\x2', '\x2', '\x9E', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', '\x64', '\x2', '\x2', '\xA0', 
		'\xA1', '\a', 't', '\x2', '\x2', '\xA1', '\xA2', '\a', 'g', '\x2', '\x2', 
		'\xA2', '\xA3', '\a', '\x63', '\x2', '\x2', '\xA3', '\xA4', '\a', 'm', 
		'\x2', '\x2', '\xA4', ':', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', 
		'\a', '\x66', '\x2', '\x2', '\xA6', '\xA7', '\a', 'g', '\x2', '\x2', '\xA7', 
		'\xA8', '\a', 'h', '\x2', '\x2', '\xA8', '\xA9', '\a', 'k', '\x2', '\x2', 
		'\xA9', '\xAA', '\a', 'p', '\x2', '\x2', '\xAA', '\xAB', '\a', 'g', '\x2', 
		'\x2', '\xAB', '<', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\a', 
		'q', '\x2', '\x2', '\xAD', '\xAE', '\a', 't', '\x2', '\x2', '\xAE', '\xAF', 
		'\a', 'i', '\x2', '\x2', '\xAF', '>', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xB2', '\t', '\x2', '\x2', '\x2', '\xB1', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'@', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\a', '\x32', '\x2', 
		'\x2', '\xB6', '\xB7', '\a', 'z', '\x2', '\x2', '\xB7', '\xB9', '\x3', 
		'\x2', '\x2', '\x2', '\xB8', '\xBA', '\t', '\x3', '\x2', '\x2', '\xB9', 
		'\xB8', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBC', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\x42', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xBE', '\a', '\x32', '\x2', '\x2', '\xBE', '\xBF', '\a', '\x64', '\x2', 
		'\x2', '\xBF', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC2', '\t', 
		'\x4', '\x2', '\x2', '\xC1', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC2', 
		'\xC3', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC1', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC4', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\xC5', '\xCA', '\a', '$', '\x2', '\x2', '\xC6', 
		'\xC9', '\x5', 'M', '\'', '\x2', '\xC7', '\xC9', '\x5', 'O', '(', '\x2', 
		'\xC8', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC7', '\x3', '\x2', 
		'\x2', '\x2', '\xC9', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xC8', 
		'\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', '\x2', '\x2', '\x2', 
		'\xCB', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCA', '\x3', '\x2', 
		'\x2', '\x2', '\xCD', '\xCE', '\a', '$', '\x2', '\x2', '\xCE', '\x46', 
		'\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\a', '\x31', '\x2', '\x2', 
		'\xD0', '\xD1', '\a', '\x31', '\x2', '\x2', '\xD1', '\xD5', '\x3', '\x2', 
		'\x2', '\x2', '\xD2', '\xD4', '\n', '\x5', '\x2', '\x2', '\xD3', '\xD2', 
		'\x3', '\x2', '\x2', '\x2', '\xD4', '\xD7', '\x3', '\x2', '\x2', '\x2', 
		'\xD5', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD6', '\x3', '\x2', 
		'\x2', '\x2', '\xD6', '\xD8', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD5', 
		'\x3', '\x2', '\x2', '\x2', '\xD8', '\xD9', '\b', '$', '\x2', '\x2', '\xD9', 
		'H', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDE', '\t', '\x6', '\x2', '\x2', 
		'\xDB', '\xDD', '\t', '\a', '\x2', '\x2', '\xDC', '\xDB', '\x3', '\x2', 
		'\x2', '\x2', '\xDD', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xDC', 
		'\x3', '\x2', '\x2', '\x2', '\xDE', '\xDF', '\x3', '\x2', '\x2', '\x2', 
		'\xDF', 'J', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xDE', '\x3', '\x2', 
		'\x2', '\x2', '\xE1', '\xE3', '\t', '\b', '\x2', '\x2', '\xE2', '\xE1', 
		'\x3', '\x2', '\x2', '\x2', '\xE3', '\xE4', '\x3', '\x2', '\x2', '\x2', 
		'\xE4', '\xE2', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE5', '\x3', '\x2', 
		'\x2', '\x2', '\xE5', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE7', 
		'\b', '&', '\x2', '\x2', '\xE7', 'L', '\x3', '\x2', '\x2', '\x2', '\xE8', 
		'\xE9', '\a', '^', '\x2', '\x2', '\xE9', '\xEA', '\t', '\t', '\x2', '\x2', 
		'\xEA', 'N', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xEC', '\n', '\n', '\x2', 
		'\x2', '\xEC', 'P', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', '\xB3', '\xBB', 
		'\xC3', '\xC8', '\xCA', '\xD5', '\xDE', '\xE4', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
