//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Daniel\winrepos\logix\examples\d2\d2-plugin\code\D2C\D2C.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="D2CParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ID2CVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] D2CParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.preprocessordir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreprocessordir([NotNull] D2CParser.PreprocessordirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.preprodirs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreprodirs([NotNull] D2CParser.PreprodirsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncdef([NotNull] D2CParser.FuncdefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] D2CParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.paramlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamlist([NotNull] D2CParser.ParamlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamdecl([NotNull] D2CParser.ParamdeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] D2CParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.vardecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVardecl([NotNull] D2CParser.VardeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] D2CParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.funccall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunccall([NotNull] D2CParser.FunccallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArglist([NotNull] D2CParser.ArglistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.ifstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfstatement([NotNull] D2CParser.IfstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.ifstatementelse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfstatementelse([NotNull] D2CParser.IfstatementelseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.retstm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetstm([NotNull] D2CParser.RetstmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.whileloop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileloop([NotNull] D2CParser.WhileloopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLvalue([NotNull] D2CParser.LvalueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.rvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRvalue([NotNull] D2CParser.RvalueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.prefixop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixop([NotNull] D2CParser.PrefixopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.postfixop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixop([NotNull] D2CParser.PostfixopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.binop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinop([NotNull] D2CParser.BinopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] D2CParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.puretype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPuretype([NotNull] D2CParser.PuretypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="D2CParser.pointertype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointertype([NotNull] D2CParser.PointertypeContext context);
}
